[package]
name = "eth-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
env_logger = "0.9"
log = "0.4"
maplit = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres", "chrono"] }
tokio = { version = "1", features = ["full"] }
ureq = { version = "2", features = ["json"] }
