[package]
name = "eth-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-tungstenite = {version="0.17", features = ["tokio-runtime"]}
chrono = "0.4"
console = "0.15"
csv = "1"
dialoguer = "0.10"
env_logger = "0.9"
futures = "0.3"
lazy_static = "1"
num-bigint = "0.4"
pit-wall = "0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_qs = "0.9"
serial_test = "0.7.0"
sqlx = { version = "0.5", features = [
  "chrono",
  "json",
  "offline",
  "postgres",
  "runtime-tokio-native-tls",
] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
web3 = "*"

[dev-dependencies]
serial_test = "*"
