name: deploy-staging

on:
  push:
    tags:
      - "stag-*"

env:
  CARGO_TERM_COLOR: always
  BEACON_URL: http://***REMOVED***
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  GLASSNODE_API_KEY: ${{ secrets.GLASSNODE_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud/ultrasoundmoney
          username: ${{ secrets.SCALEWAY_API_KEY }}
          password: ${{ secrets.SCALEWAY_API_KEY }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rg.fr-par.scw.cloud/ultrasoundmoney/eth-analysis
          tags: |
            type=raw,latest
            type=sha,prefix=
      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  deploy-k8s-resources-dev:
    name: deploy k8s resources dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: apply -f k8s/overlays/dev
  deploy-k8s-resources-stag:
    name: deploy k8s resources staging
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: apply -f k8s/stag
  deploy-sync-beacon-states-dev:
    name: deploy dev sync-beacon-states
    runs-on: ubuntu-latest
    needs: [deploy-k8s-resources-dev, deploy-k8s-resources-stag]
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: -n dev set image cronjob/sync-beacon-states sync-beacon-states=rg.fr-par.scw.cloud/ultrasoundmoney/eth-analysis:${{ steps.vars.outputs.sha_short }}
      - name: run job
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: -n dev create job --from=cronjob/sync-beacon-states sync-beacon-states-${{ steps.vars.outputs.sha_short }}
  deploy-sync-beacon-states:
    name: deploy sync-beacon-states
    runs-on: ubuntu-latest
    needs: [deploy-k8s-resources-dev, deploy-k8s-resources-stag]
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: set image cronjob/sync-beacon-states sync-beacon-states=rg.fr-par.scw.cloud/ultrasoundmoney/eth-analysis:${{ steps.vars.outputs.sha_short }}
      - name: run job
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: create job --from=cronjob/sync-beacon-states sync-beacon-states-${{ steps.vars.outputs.sha_short }}
  deploy-update-validator-rewards:
    name: deploy update-validator-rewards
    runs-on: ubuntu-latest
    needs: [deploy-k8s-resources-dev, deploy-k8s-resources-stag]
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: set image cronjob/update-validator-rewards update-validator-rewards=rg.fr-par.scw.cloud/ultrasoundmoney/eth-analysis:${{ steps.vars.outputs.sha_short }}
      - name: run job
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: create job --from=cronjob/update-validator-rewards update-validator-rewards-${{ steps.vars.outputs.sha_short }}
  deploy-update-supply-projection-inputs:
    name: deploy update-supply-projection-inputs
    runs-on: ubuntu-latest
    needs: [deploy-k8s-resources-dev, deploy-k8s-resources-stag]
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: set image cronjob/update-supply-projection-inputs update-supply-projection-inputs=rg.fr-par.scw.cloud/ultrasoundmoney/eth-analysis:${{ steps.vars.outputs.sha_short }}
      - name: run job
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: create job --from=cronjob/update-supply-projection-inputs update-supply-projection-inputs-${{ steps.vars.outputs.sha_short }}
